blank_issues_enabled: false
contact_links:
  - name: ya-corps issue tracker
    url: https://github.com/An0n-00/ya-corps/issues
    about: For support, questions, or help, visit the ya-corps issue tracker.